GET http://localhost:5000/users

###

GET http://localhost:5000/users/64a5a6ff4c2a2594ff7f5f7a


###
POST http://localhost:5000/users
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "name": "John Doe", 
    "hash": "12345678"
}

###

PUT  http://localhost:5000/users/64a5a6ff4c2a2594ff7f5f7a
content-type: application/json

{
    "hash": "123456789"
}

###

DELETE   http://localhost:5000/users/64a5a6ff4c2a2594ff7f5f7a